In [ ]:
import numpy as np

empty_array = np.empty((2,2))
print(empty_array)

[[4.84442705e-310 0.00000000e+000]
 [4.84324875e-310 6.88881037e-310]]


In [ ]:
import numpy as np

ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

filled_array = np.full((3, 5), 9)
print(filled_array)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [ ]:
import numpy as np

original_array = np.array([[1, 2], [3, 4], [5,6]])

zeros_array = np.zeros_like(original_array)
print(zeros_array)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
import numpy as np

original_array = np.array([[1, 2], [3, 4]])

ones_array = np.ones_like(original_array)
print(ones_array)

[[1 1]
 [1 1]]


In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]

numpy_array = np.array(new_list)
print(numpy_array)


[1 2 3 4]


In [ ]:
import numpy as np

array_range = np.arange(10, 50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np

matrix3x3 = np.arange(9).reshape(3,3)
print(matrix3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

random_array = np.random.random(30)

array_mean = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", array_mean)

Random Array: [0.90194955 0.2958628  0.73556797 0.373304   0.19270826 0.10390279
 0.55098612 0.6325474  0.81458712 0.7096229  0.51160908 0.6934913
 0.65528062 0.84494295 0.22639448 0.91977653 0.15167487 0.12384516
 0.1791533  0.04611074 0.28304405 0.3366826  0.75395779 0.57030658
 0.2830948  0.67053403 0.9325251  0.63106907 0.48962659 0.19460936]
Mean of the Array: 0.4936255959214154


In [ ]:
import numpy as np

random_array = np.random.random((10, 10))

min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

Random 10x10 Array:
[[0.0866648  0.41423309 0.49138246 0.23278318 0.45090058 0.41491256
  0.85363966 0.82761102 0.1568812  0.04031266]
 [0.99936199 0.21210709 0.79008814 0.98397879 0.05650833 0.50272489
  0.01635359 0.71085438 0.48570778 0.46487217]
 [0.63570741 0.98716406 0.12673861 0.57780819 0.27270706 0.23837887
  0.59230803 0.43057123 0.91469022 0.65346139]
 [0.91731656 0.28161622 0.0041309  0.28092692 0.6435923  0.07249001
  0.56187295 0.87048649 0.69299291 0.14877722]
 [0.92959586 0.27173268 0.28648608 0.76289317 0.36000891 0.76453405
  0.67088936 0.59604982 0.04852807 0.07994221]
 [0.40682109 0.99394342 0.84907002 0.24758754 0.83420609 0.44650506
  0.92892202 0.05963173 0.71381576 0.70633242]
 [0.88662339 0.65781024 0.3211844  0.80920349 0.06338027 0.81333411
  0.75401323 0.19225885 0.21278111 0.02665572]
 [0.90855202 0.01240633 0.26746491 0.69846351 0.53419095 0.79998689
  0.53663701 0.0743334  0.41709009 0.15801004]
 [0.71200506 0.14273923 0.45600955 0.90567079 0.28815419 0.4

In [ ]:
import numpy as np

zero_array = np.zeros(10)

zero_array[4] = 1

print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

arr = [1, 2, 0, 0, 4, 0]

reversed_arr = arr[::-1]
reversed_arr

[0, 4, 0, 0, 2, 1]

In [ ]:
import numpy as np
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
border_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard



array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

sum_xy = np.add(x, y)
sum_xy

array([[ 6,  8],
       [10, 13]])

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

diff_vw = np.subtract(v, w)
diff_vw

array([-2, -2])

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

mul_v = x * 3
mul_v

array([[ 3,  6],
       [ 9, 15]])

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

square_w = np.square(w)
square_w

array([121, 144])

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)

dot_xv = np.dot(x, v)

dot_xy = np.dot(x, y)

(dot_vw, dot_xv, dot_xy)

(219,
 array([29, 77]),
 array([[19, 22],
        [50, 58]]))

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_xy_row = np.concatenate((x, y), axis=0)

concat_vw_col = np.vstack((v, w))
concat_xy_row, concat_vw_col

(array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)

concat_xv_error
#all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)'

'all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)'

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1 = I:")
print(I)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:")
print(AB)
print("BA:")
print(BA)
print("AB == BA:", np.array_equal(AB, BA))

AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:")
print(AB_T)
print("B^T * A^T:")
print(BT_AT)
print("(AB)^T == B^T * A^T:", np.array_equal(AB_T, BT_AT))
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_system = np.array([-1, -3, 9])

A_inv_system = np.linalg.inv(A_system)
X = np.dot(A_inv_system, B_system)
print("Solution to the system of equations using inverse method:")
print(X)


A * A^-1 = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
AB == BA: False
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
(AB)^T == B^T * A^T: True
Solution to the system of equations using inverse method:
[ 2.  1. -2.]


In [ ]:
import time
import numpy as np

list1, list2 = [i for i in range(1000000)], [i for i in range(1000000)]
start = time.time()
result_list_add = [list1[i] + list2[i] for i in range(1000000)]
print(f"List Addition Time: {time.time() - start:.4f} seconds")

array1, array2 = np.arange(1000000), np.arange(1000000)
start = time.time()
result_array_add = array1 + array2
print(f"NumPy Addition Time: {time.time() - start:.4f} seconds")

start = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(1000000)]
print(f"List Multiplication Time: {time.time() - start:.4f} seconds")

start = time.time()
result_array_mul = array1 * array2
print(f"NumPy Multiplication Time: {time.time() - start:.4f} seconds")

start = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
print(f"List Dot Product Time: {time.time() - start:.4f} seconds")

start = time.time()
dot_product_array = np.dot(array1, array2)
print(f"NumPy Dot Product Time: {time.time() - start:.4f} seconds")

matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i + j for j in range(1000)] for i in range(1000)]
start = time.time()
result_matrix_mul_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
print(f"List Matrix Multiplication Time: {time.time() - start:.4f} seconds")

matrix1_np, matrix2_np = np.random.rand(1000, 1000), np.random.rand(1000, 1000)
start = time.time()
result_matrix_mul_np = np.dot(matrix1_np, matrix2_np)
print(f"NumPy Matrix Multiplication Time: {time.time() - start:.4f} seconds")


List Addition Time: 0.1707 seconds
NumPy Addition Time: 0.0041 seconds
List Multiplication Time: 0.1765 seconds
NumPy Multiplication Time: 0.0049 seconds
List Dot Product Time: 0.1564 seconds
NumPy Dot Product Time: 0.0019 seconds
List Matrix Multiplication Time: 255.0887 seconds
NumPy Matrix Multiplication Time: 0.0624 seconds
